spring.application.name=productManagement
spring.datasource.url=jdbc:h2:mem:products-db
spring.datasource.username=Lyrach
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085
spring.h2.console.enabled=true